apiVersion: v2
name: crud-chart
description: A Helm chart for install CRUD app

type: application

version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: postgresql
    version: 8.7.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - crud-postgres
