apiVersion: v2
name: apigateway-identity-chart
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - identity-database
