apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apigateway-identity-chart.fullname" . }}
  labels:
  {{- include "apigateway-identity-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apigateway-identity-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apigateway-identity-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: spring.datasource.url
              valueFrom:
                secretKeyRef:
                  name: {{ include "apigateway-identity-chart.fullname" . }}-secret
                  key: DB_URL
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: {{ include "apigateway-identity-chart.fullname" . }}-secret
                  key: DB_USERNAME
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: {{ include "apigateway-identity-chart.fullname" . }}-secret
                  key: DB_PASSWORD
