apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: nao4j/health-check
    context: health-check
deploy:
  kubectl:
    manifests:
    - deployment.yml
    - service.yml
    - ingress.yml
