= Домашнее задание к лекции "Backend for frontends. API Gateway"

== Текст задания

В этом ДЗ вы научитесь добавлять в приложение аутентификацию и регистрацию пользователей.

Добавить в приложение аутентификацию и регистрацию пользователей.

Реализовать сценарий "Изменение и просмотр данных в профиле клиента". Пользователь регистрируется. Заходит под собой и по определенному урлу получает данные о своем профиле. Может поменять данные в профиле. Данные профиля для чтения и редактирования не должны быть доступны другим клиентам (аутентифицированным или нет).

На выходе должны быть:

. Описание архитектурного решения и схема взаимодействия сервисов (в виде картинки)
. Команда установки приложения (из helm-а или из манифестов). Обязательно указать в каком namespace нужно устанавливать.
. Команда установки api-gateway, если он отличен от nginx-ingress.
. Тесты постмана, которые прогоняют сценарий:
.. Регистрация пользователя 1
.. Проверка, что изменение и получение профиля пользователя недоступно без логина
.. Вход пользователя 1
.. Изменение профиля пользователя 1
.. Проверка, что профиль поменялся
.. Выход (если есть)
.. Регистрация пользователя 2
.. Вход пользователя 2
.. Проверка, что пользователь 2 не имеет доступа на чтение и редактирование профиля пользователя1
.. В тестах обязательно:
... Наличие {{baseUrl}} для урла
... Использование домена arch.homework в качестве initial значения {{baseUrl}}
... Использование сгенерированных случайно данных в сценарии
... Отображение данных запроса и данных ответа при запуске из командной строки с помощью newman

== Проверка задания

=== Namespace

[source,bash]
----
kubectl create namespace myapp
kubectl config set-context --current --namespace=myapp
----

=== Установка Ambassador AES

[source,bash]
----
helm repo add datawire https://getambassador.io
helm install aes datawire/ambassador -f ambassador_values.yaml
----

=== Деплой приложения apigateway-idently

[source,bash]
----
helm install apigateway-idently ./apigateway-idently/apigateway-identity-chart
----

=== Деплой приложения apigateway-simple-app

[source,bash]
----
helm install apigateway-simple-app ./apigateway-simple-app/apigateway-simple-app-chart
----

=== Применение манифестов Ambassador

[source,bash]
----
kubectl apply -f ambassador/
----

=== Запуск тестов

[source,bash]
----
newman run --env-var "baseUrl=http://{{minikube ip}}:{{aes-ambassador http port}}" test.postman_collection.json
----
