= Домашнее задание к лекции "Основы работы с Kubernetes (часть 3)"

== Текст задания

. Сделать простейший RESTful CRUD по созданию, удалению, просмотру и обновлению пользователей.
Пример API - https://app.swaggerhub.com/apis/otus55/users/1.0.0
. Добавить базу данных для приложения
.. Базу данных установить helm-ом из одного из репозиториев чартов (желательно официальных)
.. Конфигурация приложения должна хранится в Configmaps
.. Доступы к БД должны храниться в Secrets
. Первоначальные миграции должны быть оформлены в качестве Job-ы, если это требуется
. Ingress-ы должны также вести на url arch.homework/otusapp/{student-name}/* (как и в прошлом задании)

На выходе должны быть предоставлена:

. ссылка на директорию в github, где находится директория с манифестами кубернетеса
. инструкция по запуску приложения
.. команда установки БД из helm, вместе с файлом values.yaml.
.. команда применения первоначальных миграций
.. команда kubectl apply -f, которая запускает в правильном порядке манифесты кубернетеса
. Postman коллекция, в которой будут представлены примеры запросов к сервису на создание, получение, изменение и
удаление пользователя. Важно: в postman коллекции использовать базовый url - arch.homework.


Задание со звездочкой:

+3 балла за шаблонизацию приложения в helm 3 чартах

+2 балла за использование официального helm чарта для БД и подключение его в чарт приложения в качестве зависимости

== Сборка образа

```
docker build -t crud:1.0.0 .
```

== Деплой в Docker Hub

```
docker login
docker tag crud:1.0.0 nao4j/crud:1.0.0
docker push nao4j/crud:1.0.0
```

== Запуск образа

```
docker run -p 8080:8080 nao4j/crud:1.0.0 --env POSTGRES_URL= --env POSTGRES_USER= --env POSTGRES_PASSWORD=
```

== Проверка задания

=== Установка зависимостей

```
helm dependency update ./crud-chart
```

=== Установка Helm-чарта

```
helm install crud-app ./crud-chart
```

=== Проверка работоспособности

```
curl http://arch.homework/otusapp/epilipenko/actuator/health
```

=== Postman-коллекция

```
crud.postman_collection.json
```
