apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: "myapp-jwt-filter"
spec:
  JWT:
    jwksURI: "http://apigateway-identity:9000/.well-known/jwks.json"
    insecureTLS: true
    renegotiateTLS: freelyAsClient
    validAlgorithms:
      - "RS256"
    requireAudience: false
    requireIssuer: false
    requireIssuedAt: false
    requireExpiresAt: false
    requireNotBefore: false
    injectRequestHeaders:
      - name: "X-User-Login"
        value: "{{ .token.Claims.sub }}"
      - name: "X-User-First-Name"
        value: "{{ .token.Claims.first_name }}"
      - name: "X-User-Last-Name"
        value: "{{ .token.Claims.last_name }}"
